# Copyright (c) 2014 Alexander Lamaison <alexander.lamaison@gmail.com>
#
# Redistribution and use in source and binary forms,
# with or without modification, are permitted provided
# that the following conditions are met:
#
#   Redistributions of source code must retain the above
#   copyright notice, this list of conditions and the
#   following disclaimer.
#
#   Redistributions in binary form must reproduce the above
#   copyright notice, this list of conditions and the following
#   disclaimer in the documentation and/or other materials
#   provided with the distribution.
#
#   Neither the name of the copyright holder nor the names
#   of any other contributors may be used to endorse or
#   promote products derived from this software without
#   specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.

dist: xenial

sudo: required

services:
  - docker

language: c

compiler:
  - gcc
  - clang

addons:
  chrome: stable
matrix:
  include:
    - name: "Check style"
      install: ~
      script: ./ci/checksrc.sh

    - name: "Package"
      script:
        - ./ci/build.sh
        - cd build && cmake --build . --target package

env:
  - CRYPTO_BACKEND=OpenSSL ADDRESS_SIZE=64
  - CRYPTO_BACKEND=OpenSSL ADDRESS_SIZE=32
  - CRYPTO_BACKEND=mbedTLS ADDRESS_SIZE=64 LEAK_CHECK=valgrind
  - CRYPTO_BACKEND=mbedTLS ADDRESS_SIZE=32
  - CRYPTO_BACKEND=Libgcrypt ADDRESS_SIZE=64
  - CRYPTO_BACKEND=Libgcrypt ADDRESS_SIZE=32
  - ENABLE_ZLIB_COMPRESSION=OFF
  - ENABLE_ZLIB_COMPRESSION=ON

install: ./ci/setup.sh

script:
  - ./ci/build.sh
  - ./ci/test.sh

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
    only:
        - master
